version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=aierp
      - USE_REAL_LLM=false
    depends_on:
      - mongo
    ports:
      - "3127:3127"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm i && npm run build && npx vite preview --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:


