# backend/app/schemas/sap_work_report.py
from pydantic import BaseModel, Field
from datetime import date, datetime
from typing import Optional, Dict, Any
from enum import Enum

# AFKO - 订单主数据表
class AFKOBase(BaseModel):
    mandt: str = Field(..., description="客户端")
    aufnr: str = Field(..., description="订单号")
    gltrp: Optional[date] = Field(None, description="基本完成日期")
    gstrp: Optional[date] = Field(None, description="基本开始日期")
    ftrms: Optional[date] = Field(None, description="实际开始日期")
    gltrs: Optional[date] = Field(None, description="计划完成日期")
    gstrs: Optional[date] = Field(None, description="计划开始日期")
    gstri: Optional[date] = Field(None, description="实际开始日期")
    getri: Optional[date] = Field(None, description="实际完成日期")
    gltri: Optional[date] = Field(None, description="实际完成日期")
    ftrmi: Optional[date] = Field(None, description="实际开始日期")
    ftrmp: Optional[date] = Field(None, description="实际开始日期")
    rsnum: Optional[str] = Field(None, description="预留号")
    gasmg: Optional[float] = Field(None, description="已确认数量")
    gamng: Optional[float] = Field(None, description="订单数量")
    gmein: Optional[str] = Field(None, description="基本计量单位")
    plnbez: Optional[str] = Field(None, description="物料号")
    plnty: Optional[str] = Field(None, description="计划类型")
    plnnr: Optional[str] = Field(None, description="计划号")
    plnaw: Optional[str] = Field(None, description="计划版本")
    plnal: Optional[str] = Field(None, description="计划版本")
    pverw: Optional[str] = Field(None, description="计划版本")

class AFKOCreate(AFKOBase):
    pass

class AFKOResponse(AFKOBase):
    id: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

# AFPO - 订单项目表
class AFPOBase(BaseModel):
    mandt: str = Field(..., description="客户端")
    aufnr: str = Field(..., description="订单号")
    posnr: str = Field(..., description="项目号")
    psobs: Optional[str] = Field(None, description="项目类别")
    qunum: Optional[str] = Field(None, description="配额号")
    qupos: Optional[str] = Field(None, description="配额项目")
    projn: Optional[str] = Field(None, description="项目号")
    plnum: Optional[str] = Field(None, description="计划号")
    strmp: Optional[date] = Field(None, description="计划开始日期")
    etrmp: Optional[date] = Field(None, description="计划完成日期")
    kdauf: Optional[str] = Field(None, description="销售订单号")
    kdpos: Optional[str] = Field(None, description="销售订单项目")
    kdein: Optional[str] = Field(None, description="销售订单项目")
    beskz: Optional[str] = Field(None, description="采购类型")
    psamg: Optional[float] = Field(None, description="计划数量")
    psmng: Optional[float] = Field(None, description="计划数量")
    wemng: Optional[float] = Field(None, description="已确认数量")
    iamng: Optional[float] = Field(None, description="已确认数量")
    amein: Optional[str] = Field(None, description="计量单位")
    meins: Optional[str] = Field(None, description="基本计量单位")
    matnr: Optional[str] = Field(None, description="物料号")
    pamng: Optional[float] = Field(None, description="计划数量")
    pgmng: Optional[float] = Field(None, description="计划数量")
    knttp: Optional[str] = Field(None, description="科目分配类别")
    tpauf: Optional[str] = Field(None, description="订单号")
    ltrmi: Optional[date] = Field(None, description="实际开始日期")
    ltrmp: Optional[date] = Field(None, description="实际开始日期")
    kalnr: Optional[str] = Field(None, description="成本核算号")
    uebto: Optional[str] = Field(None, description="转换因子")
    uebtk: Optional[str] = Field(None, description="转换因子")
    untto: Optional[str] = Field(None, description="转换因子")
    insmk: Optional[str] = Field(None, description="库存标识")
    wepos: Optional[str] = Field(None, description="确认标识")
    bwtar: Optional[str] = Field(None, description="评估类型")
    bwty: Optional[str] = Field(None, description="评估类型")
    pwerk: Optional[str] = Field(None, description="工厂")
    lgort: Optional[str] = Field(None, description="库存地点")
    umrez: Optional[str] = Field(None, description="转换因子")
    umren: Optional[str] = Field(None, description="转换因子")
    webaz: Optional[str] = Field(None, description="转换因子")
    elikz: Optional[str] = Field(None, description="交货完成标识")
    safnr: Optional[str] = Field(None, description="销售订单号")
    verid: Optional[str] = Field(None, description="版本")
    sernr: Optional[str] = Field(None, description="序列号")
    techs: Optional[str] = Field(None, description="技术标识")
    dwerk: Optional[str] = Field(None, description="目标工厂")
    dauty: Optional[str] = Field(None, description="目标订单类型")
    dauat: Optional[str] = Field(None, description="目标订单类型")
    dgltp: Optional[date] = Field(None, description="目标计划开始日期")
    dglts: Optional[date] = Field(None, description="目标计划完成日期")
    dfrei: Optional[str] = Field(None, description="目标释放标识")
    dnrel: Optional[str] = Field(None, description="目标释放标识")
    verto: Optional[str] = Field(None, description="转换标识")
    sobkz: Optional[str] = Field(None, description="特殊库存标识")
    kzvbr: Optional[str] = Field(None, description="消耗标识")
    wewrt: Optional[float] = Field(None, description="确认值")
    weunb: Optional[str] = Field(None, description="确认单位")
    ablad: Optional[str] = Field(None, description="卸货点")
    wempf: Optional[str] = Field(None, description="收货人")
    charg: Optional[str] = Field(None, description="批次号")
    gsber: Optional[str] = Field(None, description="业务范围")
    weaed: Optional[date] = Field(None, description="确认日期")
    cuobj: Optional[str] = Field(None, description="配置对象")
    kbnkz: Optional[str] = Field(None, description="科目分配标识")
    arsnr: Optional[str] = Field(None, description="预留号")
    arsps: Optional[str] = Field(None, description="预留项目")
    krsnr: Optional[str] = Field(None, description="成本核算号")
    krsp: Optional[str] = Field(None, description="成本核算项目")
    kckey: Optional[str] = Field(None, description="成本核算键")
    rtp01: Optional[str] = Field(None, description="预留字段1")
    rtp02: Optional[str] = Field(None, description="预留字段2")
    rtp03: Optional[str] = Field(None, description="预留字段3")
    rtp04: Optional[str] = Field(None, description="预留字段4")
    ksvon: Optional[str] = Field(None, description="成本核算开始")
    ksbis: Optional[str] = Field(None, description="成本核算结束")
    objnp: Optional[str] = Field(None, description="对象号")
    ndisr: Optional[str] = Field(None, description="分发标识")
    vfmng: Optional[float] = Field(None, description="确认数量")
    gsbtr: Optional[float] = Field(None, description="确认值")
    kzavc: Optional[str] = Field(None, description="AVC标识")
    kzbws: Optional[str] = Field(None, description="BWS标识")
    xloek: Optional[str] = Field(None, description="删除标识")
    sernp: Optional[str] = Field(None, description="序列号项目")
    anzsn: Optional[str] = Field(None, description="序列号数量")
    objtype: Optional[str] = Field(None, description="对象类型")
    ch_proc: Optional[str] = Field(None, description="变更处理")
    fxpr: Optional[str] = Field(None, description="固定价格")
    cuobj_root: Optional[str] = Field(None, description="根配置对象")
    berid: Optional[str] = Field(None, description="MRP区域")
    techs_copy: Optional[str] = Field(None, description="技术标识副本")
    sgt_scat: Optional[str] = Field(None, description="SGT类别")
    kunnr2: Optional[str] = Field(None, description="客户号2")
    mill_oc_aufnr_u: Optional[str] = Field(None, description="Mill OC订单号U")
    mill_oc_rumng: Optional[float] = Field(None, description="Mill OC数量")
    mill_oc_sort: Optional[str] = Field(None, description="Mill OC排序")
    ebel: Optional[str] = Field(None, description="采购订单号")

class AFPOCreate(AFPOBase):
    pass

class AFPOResponse(AFPOBase):
    id: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

# AFVC - 订单工序表
class AFVCBase(BaseModel):
    mandt: str = Field(..., description="客户端")
    aufpl: str = Field(..., description="订单计划")
    aplzl: str = Field(..., description="计划项目")
    plnfl: Optional[float] = Field(None, description="计划浮动")
    plnkn: Optional[float] = Field(None, description="计划节点")
    plnal: Optional[str] = Field(None, description="计划版本")
    plnty: Optional[str] = Field(None, description="计划类型")
    vintv: Optional[str] = Field(None, description="版本间隔")
    plnnr: Optional[str] = Field(None, description="计划号")
    zaehl: Optional[str] = Field(None, description="计数器")
    vornr: Optional[str] = Field(None, description="工序号")
    steus: Optional[str] = Field(None, description="控制码")
    arbid: Optional[str] = Field(None, description="工作中心")
    pdest: Optional[str] = Field(None, description="目标工厂")
    werks: Optional[str] = Field(None, description="工厂")
    ktsch: Optional[str] = Field(None, description="成本中心")
    ltxa1: Optional[str] = Field(None, description="工序短文本")
    ltxa2: Optional[str] = Field(None, description="工序长文本")
    txtsp: Optional[str] = Field(None, description="文本语言")
    vplty: Optional[str] = Field(None, description="计划类型")
    vplnr: Optional[str] = Field(None, description="计划号")
    vplal: Optional[str] = Field(None, description="计划版本")
    vplfl: Optional[str] = Field(None, description="计划浮动")
    vgwts: Optional[str] = Field(None, description="版本权重")
    lar01: Optional[str] = Field(None, description="工作中心1")
    lar02: Optional[str] = Field(None, description="工作中心2")
    lar03: Optional[str] = Field(None, description="工作中心3")
    lar04: Optional[str] = Field(None, description="工作中心4")
    lar05: Optional[str] = Field(None, description="工作中心5")
    lar06: Optional[str] = Field(None, description="工作中心6")
    zerma: Optional[str] = Field(None, description="控制码")
    zgdat: Optional[date] = Field(None, description="计划日期")
    zcode: Optional[str] = Field(None, description="代码")
    zulnr: Optional[str] = Field(None, description="供应商")
    loanz: Optional[str] = Field(None, description="供应商")
    loart: Optional[str] = Field(None, description="供应商类型")
    rsanz: Optional[str] = Field(None, description="预留数量")
    qualf: Optional[str] = Field(None, description="质量")
    anzma: Optional[str] = Field(None, description="数量")
    rfgrp: Optional[str] = Field(None, description="资源组")
    rfsch: Optional[str] = Field(None, description="资源调度")
    rasch: Optional[str] = Field(None, description="资源分配")
    aufak: Optional[str] = Field(None, description="订单确认")
    logrp: Optional[str] = Field(None, description="逻辑组")
    uemus: Optional[str] = Field(None, description="使用标识")
    uekan: Optional[str] = Field(None, description="使用标识")
    flies: Optional[str] = Field(None, description="流程标识")
    spmus: Optional[str] = Field(None, description="特殊标识")
    splim: Optional[str] = Field(None, description="特殊限制")
    ablipkz: Optional[str] = Field(None, description="删除标识")
    rstra: Optional[str] = Field(None, description="资源策略")
    sumnr: Optional[str] = Field(None, description="汇总号")
    sortl: Optional[str] = Field(None, description="排序")
    lifnr: Optional[str] = Field(None, description="供应商")
    preis: Optional[float] = Field(None, description="价格")
    peinh: Optional[str] = Field(None, description="价格单位")
    sakto: Optional[str] = Field(None, description="总账科目")
    waers: Optional[str] = Field(None, description="货币")
    infnr: Optional[str] = Field(None, description="信息记录号")
    esokz: Optional[str] = Field(None, description="采购标识")
    ekorg: Optional[str] = Field(None, description="采购组织")
    ekgrp: Optional[str] = Field(None, description="采购组")
    kzlgf: Optional[str] = Field(None, description="标识")
    kzwrtf: Optional[str] = Field(None, description="标识")
    matkl: Optional[str] = Field(None, description="物料组")
    ddehn: Optional[str] = Field(None, description="扩展")
    anzzl: Optional[str] = Field(None, description="数量")
    prznt: Optional[str] = Field(None, description="百分比")
    mlstn: Optional[str] = Field(None, description="物料清单")
    pprio: Optional[str] = Field(None, description="优先级")
    bukrs: Optional[str] = Field(None, description="公司代码")
    anfko: Optional[str] = Field(None, description="订单号")
    anfkokrs: Optional[str] = Field(None, description="订单号公司代码")
    indet: Optional[str] = Field(None, description="标识")
    larnt: Optional[str] = Field(None, description="工作中心")
    prkst: Optional[str] = Field(None, description="成本中心")
    aplfl: Optional[str] = Field(None, description="计划浮动")
    rueck: Optional[str] = Field(None, description="返回")
    rmzhl: Optional[str] = Field(None, description="返回计数器")
    projn: Optional[str] = Field(None, description="项目号")
    objnr: Optional[str] = Field(None, description="对象号")
    spanz: Optional[str] = Field(None, description="跨度")
    bedid: Optional[str] = Field(None, description="需求ID")
    bedzl: Optional[str] = Field(None, description="需求项目")
    banfn: Optional[str] = Field(None, description="采购申请号")
    bnfpo: Optional[str] = Field(None, description="采购申请项目")
    lek01: Optional[str] = Field(None, description="预留字段1")
    lek02: Optional[str] = Field(None, description="预留字段2")
    lek03: Optional[str] = Field(None, description="预留字段3")
    lek04: Optional[str] = Field(None, description="预留字段4")
    lek05: Optional[str] = Field(None, description="预留字段5")
    lek06: Optional[str] = Field(None, description="预留字段6")
    selkz: Optional[str] = Field(None, description="选择标识")
    kalid: Optional[str] = Field(None, description="日历ID")
    frsp: Optional[str] = Field(None, description="释放")
    stdkn: Optional[str] = Field(None, description="标准节点")
    anlzu: Optional[str] = Field(None, description="分配")
    istru: Optional[str] = Field(None, description="结构")
    isty: Optional[str] = Field(None, description="类型")
    isnr: Optional[str] = Field(None, description="号")
    istkn: Optional[str] = Field(None, description="节点")
    istpo: Optional[str] = Field(None, description="项目")
    iupoz: Optional[str] = Field(None, description="项目")
    ebort: Optional[str] = Field(None, description="地点")
    vertl: Optional[str] = Field(None, description="分配")
    leknw: Optional[str] = Field(None, description="预留字段")
    nprio: Optional[str] = Field(None, description="优先级")
    pvzkn: Optional[str] = Field(None, description="节点")
    phflg: Optional[str] = Field(None, description="标识")
    phseq: Optional[str] = Field(None, description="序列")
    knobj: Optional[str] = Field(None, description="对象")
    erfsicht: Optional[str] = Field(None, description="视图")
    qppktabs: Optional[str] = Field(None, description="表")
    otype: Optional[str] = Field(None, description="对象类型")
    objektid: Optional[str] = Field(None, description="对象ID")
    qlkapar: Optional[str] = Field(None, description="参数")
    rstuf: Optional[str] = Field(None, description="级别")
    nptxtky: Optional[str] = Field(None, description="文本键")
    subsys: Optional[str] = Field(None, description="子系统")
    pspnr: Optional[str] = Field(None, description="项目号")
    packno: Optional[str] = Field(None, description="包号")
    txjcd: Optional[str] = Field(None, description="税务代码")
    scope: Optional[str] = Field(None, description="范围")
    gsber: Optional[str] = Field(None, description="业务范围")
    prctr: Optional[str] = Field(None, description="利润中心")
    no_disp: Optional[str] = Field(None, description="不显示")
    qkzprzeit: Optional[str] = Field(None, description="时间标识")
    qkzztmg1: Optional[str] = Field(None, description="时间标识1")
    qkzprmeng: Optional[str] = Field(None, description="数量标识")
    qkzprfrei: Optional[str] = Field(None, description="释放标识")
    kzfeat: Optional[str] = Field(None, description="特征标识")
    qkztlsbest: Optional[str] = Field(None, description="最佳标识")
    aennr: Optional[str] = Field(None, description="变更号")
    cuobj_arb: Optional[str] = Field(None, description="工作配置对象")
    evgew: Optional[float] = Field(None, description="权重")
    arbii: Optional[str] = Field(None, description="工作")
    werki: Optional[str] = Field(None, description="工厂")
    cy_seqnr: Optional[str] = Field(None, description="序列号")
    kapt_puffr: Optional[str] = Field(None, description="缓冲")
    ebel: Optional[str] = Field(None, description="采购订单号")
    ebelp: Optional[str] = Field(None, description="采购订单项目")
    wempf: Optional[str] = Field(None, description="收货人")
    ablad: Optional[str] = Field(None, description="卸货点")
    clasf: Optional[str] = Field(None, description="分类")
    frunv: Optional[str] = Field(None, description="运行环境")
    zschl: Optional[str] = Field(None, description="代码")
    kalsm: Optional[str] = Field(None, description="计算方案")
    sched_end: Optional[date] = Field(None, description="计划结束日期")
    netzkont: Optional[str] = Field(None, description="网络控制")
    owaer: Optional[str] = Field(None, description="货币")
    afnam: Optional[str] = Field(None, description="申请人")
    bednr: Optional[str] = Field(None, description="需求号")
    kzfix: Optional[str] = Field(None, description="固定标识")
    pernr: Optional[str] = Field(None, description="人员号")
    frdlb: Optional[str] = Field(None, description="释放")
    qpart: Optional[str] = Field(None, description="部分")
    loekz: Optional[str] = Field(None, description="删除标识")
    wkurs: Optional[float] = Field(None, description="汇率")
    prod_act: Optional[str] = Field(None, description="生产活动")
    fplnr: Optional[str] = Field(None, description="计划号")
    objtype: Optional[str] = Field(None, description="对象类型")
    ch_proc: Optional[str] = Field(None, description="变更处理")
    klvar: Optional[str] = Field(None, description="变量")
    kalnr: Optional[str] = Field(None, description="成本核算号")
    fordn: Optional[str] = Field(None, description="订单号")
    fordp: Optional[str] = Field(None, description="订单项目")
    mat_prkst: Optional[str] = Field(None, description="物料成本中心")
    prz01: Optional[str] = Field(None, description="预留字段1")
    rfpnt: Optional[str] = Field(None, description="参考点")
    func_area: Optional[str] = Field(None, description="功能区域")
    techs: Optional[str] = Field(None, description="技术标识")
    adpsp: Optional[str] = Field(None, description="分配")
    rfippnt: Optional[str] = Field(None, description="参考点")
    mes_operid: Optional[str] = Field(None, description="MES操作ID")
    mes_stepid: Optional[str] = Field(None, description="MES步骤ID")
    cum_cuguid: Optional[str] = Field(None, description="CUM GUID")
    isdfps_objnr: Optional[str] = Field(None, description="ISDFPS对象号")
    afvc_status: Optional[str] = Field(None, description="AFVC状态")
    mill_oc_aufnr_mo: Optional[str] = Field(None, description="Mill OC订单号MO")
    wty_ind: Optional[str] = Field(None, description="WTY标识")
    tplnr: Optional[str] = Field(None, description="技术对象号")
    equnr: Optional[str] = Field(None, description="设备号")

class AFVCCreate(AFVCBase):
    pass

class AFVCResponse(AFVCBase):
    id: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

# AFVV - 订单工序时间表
class AFVVBase(BaseModel):
    mandt: str = Field(..., description="客户端")
    aufpl: str = Field(..., description="订单计划")
    aplzl: str = Field(..., description="计划项目")
    meinh: Optional[str] = Field(None, description="计量单位")
    umren: Optional[str] = Field(None, description="转换因子")
    umrez: Optional[str] = Field(None, description="转换因子")
    bmsch: Optional[str] = Field(None, description="基本调度")
    zmerh: Optional[str] = Field(None, description="时间单位")
    zeier: Optional[str] = Field(None, description="时间单位")
    vge01: Optional[str] = Field(None, description="时间单位1")
    vgw01: Optional[float] = Field(None, description="时间值1")
    vge02: Optional[str] = Field(None, description="时间单位2")
    vgw02: Optional[float] = Field(None, description="时间值2")
    vge03: Optional[str] = Field(None, description="时间单位3")
    vgw03: Optional[float] = Field(None, description="时间值3")
    vge04: Optional[str] = Field(None, description="时间单位4")
    vgw04: Optional[float] = Field(None, description="时间值4")
    vge05: Optional[str] = Field(None, description="时间单位5")
    vgw05: Optional[float] = Field(None, description="时间值5")
    vge06: Optional[str] = Field(None, description="时间单位6")
    vgw06: Optional[float] = Field(None, description="时间值6")
    zeimu: Optional[str] = Field(None, description="时间单位")
    zminu: Optional[str] = Field(None, description="时间单位")
    minwe: Optional[str] = Field(None, description="时间单位")
    zeimb: Optional[str] = Field(None, description="时间单位")
    zminb: Optional[str] = Field(None, description="时间单位")
    zeilm: Optional[str] = Field(None, description="时间单位")
    zlmax: Optional[str] = Field(None, description="时间单位")
    zeilp: Optional[str] = Field(None, description="时间单位")
    zlpro: Optional[str] = Field(None, description="时间单位")
    zeiwn: Optional[str] = Field(None, description="时间单位")
    zwnor: Optional[str] = Field(None, description="时间单位")
    zeiwm: Optional[str] = Field(None, description="时间单位")
    zwmin: Optional[str] = Field(None, description="时间单位")
    zeitn: Optional[str] = Field(None, description="时间单位")
    ztnor: Optional[str] = Field(None, description="时间单位")
    zeitm: Optional[str] = Field(None, description="时间单位")
    ztmin: Optional[str] = Field(None, description="时间单位")
    plifz: Optional[str] = Field(None, description="计划提前期")
    dauno: Optional[str] = Field(None, description="日期")
    daune: Optional[str] = Field(None, description="日期")
    daumi: Optional[str] = Field(None, description="日期")
    daume: Optional[str] = Field(None, description="日期")
    einsa: Optional[str] = Field(None, description="设置时间")
    einse: Optional[str] = Field(None, description="设置时间")
    arbei: Optional[str] = Field(None, description="工作时间")
    arbeh: Optional[str] = Field(None, description="工作时间")
    mgvrg: Optional[str] = Field(None, description="数量")
    asvrg: Optional[str] = Field(None, description="数量")
    lmnag: Optional[str] = Field(None, description="数量")
    xmnag: Optional[str] = Field(None, description="数量")
    gmnag: Optional[str] = Field(None, description="数量")
    ism01: Optional[str] = Field(None, description="标识1")
    ism02: Optional[str] = Field(None, description="标识2")
    ism03: Optional[str] = Field(None, description="标识3")
    ism04: Optional[str] = Field(None, description="标识4")
    ism05: Optional[str] = Field(None, description="标识5")
    ism06: Optional[str] = Field(None, description="标识6")
    ismnw: Optional[str] = Field(None, description="标识")
    fsavd: Optional[date] = Field(None, description="开始日期")
    fsavz: Optional[str] = Field(None, description="开始时间")
    fssbd: Optional[date] = Field(None, description="开始日期")
    fssbz: Optional[str] = Field(None, description="开始时间")
    fssad: Optional[date] = Field(None, description="开始日期")
    fssaz: Optional[str] = Field(None, description="开始时间")
    fsedd: Optional[date] = Field(None, description="结束日期")
    fsedz: Optional[str] = Field(None, description="结束时间")
    fssld: Optional[date] = Field(None, description="开始日期")
    fsslz: Optional[str] = Field(None, description="开始时间")
    fseld: Optional[date] = Field(None, description="结束日期")
    fselz: Optional[str] = Field(None, description="结束时间")
    ssavd: Optional[date] = Field(None, description="开始日期")
    ssavz: Optional[str] = Field(None, description="开始时间")
    sssbd: Optional[date] = Field(None, description="开始日期")
    sssbz: Optional[str] = Field(None, description="开始时间")
    sssad: Optional[date] = Field(None, description="开始日期")
    sssaz: Optional[str] = Field(None, description="开始时间")
    ssedd: Optional[date] = Field(None, description="结束日期")
    ssedz: Optional[str] = Field(None, description="结束时间")
    sssld: Optional[date] = Field(None, description="开始日期")
    ssslz: Optional[str] = Field(None, description="开始时间")
    sseld: Optional[date] = Field(None, description="结束日期")
    sselz: Optional[str] = Field(None, description="结束时间")
    isavd: Optional[date] = Field(None, description="开始日期")
    ieavd: Optional[date] = Field(None, description="开始日期")
    isdd: Optional[date] = Field(None, description="开始日期")
    isdz: Optional[str] = Field(None, description="开始时间")
    ierd: Optional[date] = Field(None, description="结束日期")
    ierz: Optional[str] = Field(None, description="结束时间")
    isbd: Optional[date] = Field(None, description="开始日期")
    isbz: Optional[str] = Field(None, description="开始时间")
    iebd: Optional[date] = Field(None, description="结束日期")
    iebz: Optional[str] = Field(None, description="结束时间")
    isad: Optional[date] = Field(None, description="开始日期")
    isaz: Optional[str] = Field(None, description="开始时间")
    iedd: Optional[date] = Field(None, description="结束日期")
    iedz: Optional[str] = Field(None, description="结束时间")
    pedd: Optional[date] = Field(None, description="结束日期")
    pedz: Optional[str] = Field(None, description="结束时间")
    puffr: Optional[str] = Field(None, description="缓冲")
    pufgs: Optional[str] = Field(None, description="缓冲")
    ntanf: Optional[date] = Field(None, description="开始日期")
    ntanz: Optional[str] = Field(None, description="开始时间")
    ntend: Optional[date] = Field(None, description="结束日期")
    ntenz: Optional[str] = Field(None, description="结束时间")
    ewstd: Optional[date] = Field(None, description="开始日期")
    ewstz: Optional[str] = Field(None, description="开始时间")
    ewend: Optional[date] = Field(None, description="结束日期")
    ewenz: Optional[str] = Field(None, description="结束时间")
    ewdan: Optional[str] = Field(None, description="日期")
    ewdne: Optional[str] = Field(None, description="日期")
    ewdam: Optional[str] = Field(None, description="日期")
    ewdme: Optional[str] = Field(None, description="日期")
    ewste: Optional[str] = Field(None, description="时间")
    ewsta: Optional[str] = Field(None, description="时间")
    wartz: Optional[str] = Field(None, description="等待时间")
    wrtze: Optional[str] = Field(None, description="等待时间")
    ruest: Optional[str] = Field(None, description="准备时间")
    rstze: Optional[str] = Field(None, description="准备时间")
    bearz: Optional[str] = Field(None, description="处理时间")
    beaze: Optional[str] = Field(None, description="处理时间")
    abrue: Optional[str] = Field(None, description="时间")
    aruze: Optional[str] = Field(None, description="时间")
    liegz: Optional[str] = Field(None, description="时间")
    ligze: Optional[str] = Field(None, description="时间")
    tranz: Optional[str] = Field(None, description="时间")
    traze: Optional[str] = Field(None, description="时间")
    iserh: Optional[str] = Field(None, description="时间")
    ofm01: Optional[str] = Field(None, description="标识1")
    ofm02: Optional[str] = Field(None, description="标识2")
    ofm03: Optional[str] = Field(None, description="标识3")
    ofm04: Optional[str] = Field(None, description="标识4")
    ofm05: Optional[str] = Field(None, description="标识5")
    ofm06: Optional[str] = Field(None, description="标识6")
    ofmnw: Optional[str] = Field(None, description="标识")
    bzoffb: Optional[str] = Field(None, description="标识")
    ehoffb: Optional[str] = Field(None, description="标识")
    offstb: Optional[str] = Field(None, description="标识")
    offste: Optional[str] = Field(None, description="标识")
    bzoffe: Optional[str] = Field(None, description="标识")
    ehoffe: Optional[str] = Field(None, description="标识")
    fpavd: Optional[date] = Field(None, description="开始日期")
    fpavz: Optional[str] = Field(None, description="开始时间")
    fpedd: Optional[date] = Field(None, description="结束日期")
    fpedz: Optional[str] = Field(None, description="结束时间")
    spavd: Optional[date] = Field(None, description="开始日期")
    spavz: Optional[str] = Field(None, description="开始时间")
    spedd: Optional[date] = Field(None, description="结束日期")
    spedz: Optional[str] = Field(None, description="结束时间")
    beazp: Optional[str] = Field(None, description="时间")
    pufgp: Optional[str] = Field(None, description="缓冲")
    puffp: Optional[str] = Field(None, description="缓冲")
    bearp: Optional[str] = Field(None, description="时间")
    epanf: Optional[date] = Field(None, description="开始日期")
    epanz: Optional[str] = Field(None, description="开始时间")
    epend: Optional[date] = Field(None, description="结束日期")
    epenz: Optional[str] = Field(None, description="结束时间")
    pdau: Optional[str] = Field(None, description="日期")
    pdae: Optional[str] = Field(None, description="日期")
    knote: Optional[str] = Field(None, description="节点")
    vstzw: Optional[str] = Field(None, description="时间")
    vstga: Optional[str] = Field(None, description="时间")
    qrastzeht: Optional[str] = Field(None, description="时间")
    qrastzfak: Optional[str] = Field(None, description="时间")
    qrastmeng: Optional[str] = Field(None, description="数量")
    qrastereh: Optional[str] = Field(None, description="时间")
    aufkt: Optional[str] = Field(None, description="订单类型")
    rmnag: Optional[str] = Field(None, description="数量")
    ile01: Optional[str] = Field(None, description="标识1")
    ile02: Optional[str] = Field(None, description="标识2")
    ile03: Optional[str] = Field(None, description="标识3")
    ile04: Optional[str] = Field(None, description="标识4")
    ile05: Optional[str] = Field(None, description="标识5")
    ile06: Optional[str] = Field(None, description="标识6")
    rwfak: Optional[str] = Field(None, description="因子")
    iprz1: Optional[str] = Field(None, description="标识1")
    ipre1: Optional[str] = Field(None, description="标识1")
    iprk1: Optional[str] = Field(None, description="标识1")
    takt: Optional[str] = Field(None, description="节拍")
    oprz1: Optional[str] = Field(None, description="标识1")
    opre1: Optional[str] = Field(None, description="标识1")
    pspm_indicator: Optional[str] = Field(None, description="PSPM标识")

class AFVVCreate(AFVVBase):
    pass

class AFVVResponse(AFVVBase):
    id: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

# AUFK - 订单主数据表
class AUFKBase(BaseModel):
    mandt: str = Field(..., description="客户端")
    aufnr: str = Field(..., description="订单号")
    auart: Optional[str] = Field(None, description="订单类型")
    autyp: Optional[str] = Field(None, description="订单类型")
    refnr: Optional[str] = Field(None, description="参考号")
    ernam: Optional[str] = Field(None, description="创建人")
    erdat: Optional[date] = Field(None, description="创建日期")
    aenam: Optional[str] = Field(None, description="修改人")
    aedat: Optional[date] = Field(None, description="修改日期")
    ktext: Optional[str] = Field(None, description="短文本")
    ltext: Optional[str] = Field(None, description="长文本")
    bukrs: Optional[str] = Field(None, description="公司代码")
    werks: Optional[str] = Field(None, description="工厂")
    gsber: Optional[str] = Field(None, description="业务范围")
    kokrs: Optional[str] = Field(None, description="成本控制范围")
    cckey: Optional[str] = Field(None, description="成本中心键")
    kostv: Optional[str] = Field(None, description="成本中心")
    stort: Optional[str] = Field(None, description="地点")
    sowrk: Optional[str] = Field(None, description="工厂")
    astkz: Optional[str] = Field(None, description="标识")
    waers: Optional[str] = Field(None, description="货币")
    astnr: Optional[str] = Field(None, description="订单号")
    stdat: Optional[date] = Field(None, description="开始日期")
    estnr: Optional[str] = Field(None, description="订单号")
    phas0: Optional[str] = Field(None, description="阶段0")
    phas1: Optional[str] = Field(None, description="阶段1")
    phas2: Optional[str] = Field(None, description="阶段2")
    phas3: Optional[str] = Field(None, description="阶段3")
    pdat1: Optional[date] = Field(None, description="日期1")
    pdat2: Optional[date] = Field(None, description="日期2")
    pdat3: Optional[date] = Field(None, description="日期3")
    idat1: Optional[date] = Field(None, description="日期1")
    idat2: Optional[date] = Field(None, description="日期2")
    idat3: Optional[date] = Field(None, description="日期3")
    objid: Optional[str] = Field(None, description="对象ID")
    vogrp: Optional[str] = Field(None, description="组")
    loekz: Optional[str] = Field(None, description="删除标识")
    plgkz: Optional[str] = Field(None, description="计划标识")
    kvewe: Optional[str] = Field(None, description="使用")
    kappl: Optional[str] = Field(None, description="应用")
    kalsm: Optional[str] = Field(None, description="计算方案")
    zschl: Optional[str] = Field(None, description="代码")
    abkrs: Optional[str] = Field(None, description="范围")
    kstar: Optional[str] = Field(None, description="成本要素")
    kostl: Optional[str] = Field(None, description="成本中心")
    saknr: Optional[str] = Field(None, description="总账科目")
    setnm: Optional[str] = Field(None, description="集合名")
    cycle: Optional[str] = Field(None, description="周期")
    sdate: Optional[date] = Field(None, description="开始日期")
    seqnr: Optional[str] = Field(None, description="序列号")
    user0: Optional[str] = Field(None, description="用户字段0")
    user1: Optional[str] = Field(None, description="用户字段1")
    user2: Optional[str] = Field(None, description="用户字段2")
    user3: Optional[str] = Field(None, description="用户字段3")
    user4: Optional[str] = Field(None, description="用户字段4")
    user5: Optional[str] = Field(None, description="用户字段5")
    user6: Optional[str] = Field(None, description="用户字段6")
    user7: Optional[str] = Field(None, description="用户字段7")
    user8: Optional[str] = Field(None, description="用户字段8")
    user9: Optional[str] = Field(None, description="用户字段9")
    objnr: Optional[str] = Field(None, description="对象号")
    prctr: Optional[str] = Field(None, description="利润中心")
    pspel: Optional[str] = Field(None, description="项目号")
    awsls: Optional[str] = Field(None, description="结算规则")
    abgsl: Optional[str] = Field(None, description="结算规则")
    txjcd: Optional[str] = Field(None, description="税务代码")
    func_area: Optional[str] = Field(None, description="功能区域")
    scope: Optional[str] = Field(None, description="范围")
    plint: Optional[str] = Field(None, description="计划")
    kdauf: Optional[str] = Field(None, description="销售订单号")
    kdpos: Optional[str] = Field(None, description="销售订单项目")
    aufex: Optional[str] = Field(None, description="订单扩展")
    ivpro: Optional[str] = Field(None, description="发票")
    logsystem: Optional[str] = Field(None, description="逻辑系统")
    flg_mltps: Optional[str] = Field(None, description="标识")
    abukr: Optional[str] = Field(None, description="公司代码")
    akstl: Optional[str] = Field(None, description="成本中心")
    sizecl: Optional[str] = Field(None, description="大小类别")
    izwek: Optional[str] = Field(None, description="目的")
    umwkz: Optional[str] = Field(None, description="标识")
    kstempf: Optional[str] = Field(None, description="成本中心")
    zschm: Optional[str] = Field(None, description="代码")
    pkosa: Optional[str] = Field(None, description="标识")
    anfaufnr: Optional[str] = Field(None, description="订单号")
    procnr: Optional[str] = Field(None, description="流程号")
    proty: Optional[str] = Field(None, description="流程类型")
    rsord: Optional[str] = Field(None, description="订单")
    bemot: Optional[str] = Field(None, description="动机")
    adrnra: Optional[str] = Field(None, description="地址号")
    erfzeit: Optional[str] = Field(None, description="创建时间")
    aezeit: Optional[str] = Field(None, description="修改时间")
    cstg_vrnt: Optional[str] = Field(None, description="成本变式")
    costestnr: Optional[str] = Field(None, description="成本估算号")
    veraa_user: Optional[str] = Field(None, description="用户")
    zbukrs: Optional[str] = Field(None, description="公司代码")
    zzcpkg: Optional[str] = Field(None, description="包")
    zzkhyq: Optional[str] = Field(None, description="客户要求")
    zztuhao: Optional[str] = Field(None, description="图号")
    zzjsfa: Optional[str] = Field(None, description="技术方案")
    zzxqbm: Optional[str] = Field(None, description="需求部门")
    zzyfxmh: Optional[str] = Field(None, description="研发项目号")
    zzwxy: Optional[str] = Field(None, description="物性")
    zzjy: Optional[str] = Field(None, description="检验")
    zzjyjg: Optional[str] = Field(None, description="检验结果")
    zzgzfx: Optional[str] = Field(None, description="工作分析")
    zzbf: Optional[str] = Field(None, description="标识")
    zzsernr: Optional[str] = Field(None, description="序列号")
    zzwtms: Optional[str] = Field(None, description="问题描述")
    zzgzdm: Optional[str] = Field(None, description="工作代码")
    zggyq: Optional[str] = Field(None, description="工艺要求")
    zxpl: Optional[str] = Field(None, description="计划")
    zgg: Optional[str] = Field(None, description="工艺")
    zfg: Optional[str] = Field(None, description="工艺")
    vname: Optional[str] = Field(None, description="名称")
    recid: Optional[str] = Field(None, description="记录ID")
    etype: Optional[str] = Field(None, description="类型")
    otype: Optional[str] = Field(None, description="对象类型")
    jv_jibcl: Optional[str] = Field(None, description="JIB类别")
    jv_jibsa: Optional[str] = Field(None, description="JIB标识")
    jv_oco: Optional[str] = Field(None, description="JIB OCO")
    cum_indcu: Optional[str] = Field(None, description="CUM标识")
    cum_cmnum: Optional[str] = Field(None, description="CUM号")
    cum_auest: Optional[str] = Field(None, description="CUM状态")
    cum_desnum: Optional[str] = Field(None, description="CUM描述号")
    vaplz: Optional[str] = Field(None, description="地点")
    wawrk: Optional[str] = Field(None, description="工厂")
    ferc_ind: Optional[str] = Field(None, description="标识")
    aufk_status: Optional[str] = Field(None, description="状态")
    claim_control: Optional[str] = Field(None, description="索赔控制")
    update_needed: Optional[str] = Field(None, description="需要更新")
    update_control: Optional[str] = Field(None, description="更新控制")

class AUFKCreate(AUFKBase):
    pass

class AUFKResponse(AUFKBase):
    id: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

# JEST - 对象状态表
class JESTBase(BaseModel):
    mandt: str = Field(..., description="客户端")
    objnr: str = Field(..., description="对象号")
    stat: str = Field(..., description="状态")
    inact: Optional[str] = Field(None, description="非活动")
    chgnr: Optional[str] = Field(None, description="变更号")
    dataaging: Optional[str] = Field(None, description="数据老化")

class JESTCreate(JESTBase):
    pass

class JESTResponse(JESTBase):
    id: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

# MAKT - 物料描述表
class MAKTBase(BaseModel):
    mandt: str = Field(..., description="客户端")
    matnr: str = Field(..., description="物料号")
    spras: str = Field(..., description="语言")
    maktx: Optional[str] = Field(None, description="物料描述")
    maktg: Optional[str] = Field(None, description="物料描述")

class MAKTCreate(MAKTBase):
    pass

class MAKTResponse(MAKTBase):
    id: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

# 搜索请求模型
class SAPWorkReportSearchRequest(BaseModel):
    keyword: Optional[str] = Field(None, description="搜索关键字")
    aufnr: Optional[str] = Field(None, description="订单号")
    matnr: Optional[str] = Field(None, description="物料号")
    werks: Optional[str] = Field(None, description="工厂")
    start_date: Optional[date] = Field(None, description="开始日期")
    end_date: Optional[date] = Field(None, description="结束日期")
    page: int = Field(1, ge=1, description="页码")
    size: int = Field(20, ge=1, le=100, description="每页数量")
